### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by sbuljat** [FilipBaric/pzw-pz2-FilipBaric#3]
- [ ] Ne postoji nikakva validacija polja, plaćanje je moguće uvijek. Pretpostavljam da nije tako zamišljeno. Definirati minimalan skup polja koja su obavezna i koja moraju imati određenu validaciju (npr. email, ime, prezime, broj kreditne kartice,..)
- [ ] Ispraviti pravopisne greške (Opcijonalno -> Opcionalno, Vaša kolica -> Vaša košarica, ..
- [ ] Promocijski kod ne radi, ako neka funkcionalnost nije podržana onda je radije sakrijte.
- [ ] Bez obzira koji paket odaberem cijena je uvijek ista, 1600 HRK.

**Comment by sbuljat** [comment]
Jeste pogledali ovo?

**Comment by sbuljat** [comment]
Jel možete ugraditi nekoliko validacija podataka, npr. email adresa pa ću Vam dati maksimum bodova.

**Comment by FilipBaric** [comment]
Pogledao sam ovo, ispričavam se što sam zaboravio odgovoriti. Riješio sam problem oko cijene, sada se kad se odabere određena opcija promijeni cijena. Promocijski kod je uklonjen. Stavio sam required na polja kako bih se podatci trebali u njih unit ali mi iz nekog razloga i dalje dopušta nastavak plaćanja.

**Comment by sbuljat** [comment]
U redu, zatvorit ću issue.
