### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by sbuljat** [FilipBaric/pzw-pz2-FilipBaric#4]
- [ ] Ne postoji signup forma?

**Comment by FilipBaric** [comment]
Možda ste mislili na signout koju imam kao route u app.py. To koristim kako bih izbrisao session i redirektirao nazad na index.

**Comment by sbuljat** [comment]
Mislio sam na registraciju korisnika (signup).

**Comment by sbuljat** [comment]
Zatvorit ću ovaj issue, imate formi na drugom dijelu aplikacije.
