### ISSUE TITLE
Navigacija

### ISSUE THREAD

**Issue by sbuljat** [FilipBaric/pzw-pz2-FilipBaric#5]
- [ ] http://localhost:5000/galerija.html nema dijeljenu navigaciju pa se ne možeš vratiti na Home

**Comment by FilipBaric** [comment]
Galerija ima navigaciju za nazad. Ako se pritisne u gornjem desnom kutu padajući izbornik ima navigacijske tipke za društvene mreže i nazad na početak to jest home.

**Comment by sbuljat** [comment]
To sam vidio, ali puno je intuitivnije kad je navigacija u svim dijelovima aplikacije jednolika (uniformna).
Zatvorit ću ovaj issue.
